<?php
/**
* @file
* A module that would allow users to add fields
* Created by: Andrei Ghenoiu
* Date: 8/24/12
* Resources from: http://www.pensamientosdivergentes.net/blog/modifying-contact-form-drupal-how-add-field, http://www.metaltoad.com/blog/how-add-field-drupal-contact-form
*/
function contact_add_fields_help($path, $arg){
	switch($path){
		case "admin/help#contact_add_fields":
			return '<p>'. t("allows users to add new fields to the site wide contact form - at the moment there is no option to configure it").'</p>';
			break;
	}
}
//this is what actually adds the new fields onto the form
//if you want to add more fields, just add another $form['your_new_field'] line

function contact_add_fields_form_contact_site_form_alter(&$form, &$form_state, $form_id){
	$form['location'] = array(
		'#title' => t('Your location'),
		'#type' => 'textfield',
		'#required' => TRUE,
		);
		
	$order = array('name', 'mail', 'subject','location', 'cid', 'message', 'copy', 'actions');

	foreach($order as $key => $field) {
		$form[$field]['#weight'] = $key;
	}
}

//this is where the mail being sent if edited. I just add it the the end of the 
//message

function contact_add_fields_mail_alter(&$message) {

	if ($message['id'] == 'contact_page_mail'){
		
		$message['body'][] .= t('This is their location - ').$message['params']['location'];
	}
}
		
